### PR TITLE
PEP8; added command line argument for password length; added command lin...

### PR DESCRIPTION
**Pull request by MartinThoma**
...e argument for version; added trove classifiers; added docstrings

### CODE REVIEW

**Comment by davoclavo** [comment]
Thanks Thomas!

There is an edge case where the password generator will not generate a custom length password:

```py
>>> len(generate_password(35))
32
```

That is because after the `uuid4()` call there is a string replacement that removes hyphens

**Comment by MartinThoma** [comment]
I think I fixed this issue. (my name is Martin, not "Thomas". "Thoma" (without s) is my last name)

**Comment by davoclavo** [comment]
Martin, I'm really sorry for the name mistake! I didn't even write your last name correct :disappointed: 

While the test passes, the problem persists, what about:
```py
>>> generate_password(33)
32
```

maybe we should change from `str(uuid4())` to `uuid4().hex`, which already removes the hyphens, so we won't even need to do the replacement afterwards

**Comment by MartinThoma** [comment]
> Martin, I'm really sorry for the name mistake! I didn't even write your last name correct :disappointed:

No problem.

> While the test passes, the problem persists

Ok. I thought it would only have one dash in it. I think I fixed it now and the test covers all passwords between 2 and 160 characters.

**Pull request merged**
